name: Static Tests

on:
  push:
    branches:
      - main

jobs:
  static-tests:
    name: Static Tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commit Lint
        uses: wagoid/commitlint-github-action@v5
